networks:
  roboshop:
    driver: bridge

volumes:
  mongodb:
  redis:

services:
  mongodb:
    image: mongodb
    container_name: mongodb
    volumes:
      - source: mongodb 
        target: /data/db
        type: volume

    ports:
    - "27017:27017"

  catalogue:
    image: catalogue
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis
    volumes:
      - source: redis
        target: /data
        type: volume

  cart:
    image: cart
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis

  web:
    image: web
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
    ports:
    - "80:80"

  