networks:
  roboshop:
    driver: bridge

volumes:
  mongodb:
  redis:

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - soruce: mongodb 
        target: /data/db

    ports:
      -"27017":"27017"

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis
    volumes:
      - soruce: redis
        target: /data

  cart:
    image: cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis

  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
    ports:
      -"80:80"

  