networks:
  roboshop:
    driver: bridge

volumes:
  mongodb:

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - soruce: mongodb 
        target: /data/db

    ports:
      -"27017":"27017"

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  